spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/postgres?currentSchema=public
    username: postgres
    password: d0d0l
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres	