spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://localhost:5432/postgres?currentSchema=webscheme
    username: postgres
    password: d0d0l
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres
  mail:
    host: smtp.gmail.com
    port: 587
    username: tulalit053@gmail.com
    password: feaw ckfz nsgo ldsf
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true