spring:
  datasource:
    hikari:
      maximumPoolSize: 1
    driver-class-name: org.postgresql.Driver
    url:  jdbc:postgresql://10.10.2.92:5432/postgres?currentSchema=general_ledger
    username: postgres
    password: PPU.P4ssw0rd
  jpa:    
    generate-ddl: true
    hibernate:
      ddl-auto: update
    show-sql: true    
  sql:
    init:
      mode: always
      continue-on-error: true
      platform: postgres
